- name: Download AWS cli
  run: curl "http://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
- name: Unzip AWS cli
  run: unzip awscliv2.zip
- name: Install AWS cli
  run: sudo ./aws/install
- name: Configure AWS cli
  run: |
    export AWS_ACCESS_KEY_ID= ${{ secrets.AWS_ACCESS_KEY_ID }}
    export AWS_SECRET_ACCESS_KEY = ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    export AWS_DEFAULT_REGION = ${{ env.AWS_REGION }}
    
